In [1]:
import pandas as pd

df=pd.read_csv("WSN-DS.csv")
df.head()

,id,Time,Is_CH,who CH,Dist_To_CH,ADV_S,ADV_R,JOIN_S,JOIN_R,SCH_S,SCH_R,Rank,DATA_S,DATA_R,Data_Sent_To_BS,dist_CH_To_BS,send_code,Expaned Energy,Attack type
0,101000,50,1,101000,0.00000,1,0,0,25,1,0,0,0,1200,48,130.08535,0,2.46940,Normal
1,101001,50,0,101044,75.32345,0,4,1,0,0,1,2,38,0,0,0.00000,4,0.06957,Normal
2,101002,50,0,101010,46.95453,0,4,1,0,0,1,19,41,0,0,0.00000,3,0.06898,Normal
3,101003,50,0,101044,64.85231,0,4,1,0,0,1,16,38,0,0,0.00000,4,0.06673,Normal
4,101004,50,0,101010,4.83341,0,4,1,0,0,1,25,41,0,0,0.00000,3,0.06534,Normal

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374661 entries, 0 to 374660
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0    id               374661 non-null  int64
 1    Time             374661 non-null  int64
 2    Is_CH            374661 non-null  int64
 3    who CH           374661 non-null  int64
 4    Dist_To_CH       374661 non-null  float64
 5    ADV_S            374661 non-null  int64
 6    ADV_R            374661 non-null  int64
 7    JOIN_S           374661 non-null  int64
 8    JOIN_R           374661 non-null  int64
 9    SCH_S            374661 non-null  int64
 10   SCH_R            374661 non-null  int64
 11  Rank              374661 non-null  int64
 12   DATA_S           374661 non-null  int64
 13   DATA_R           374661 non-null  int64
 14   Data_Sent_To_BS  374661 non-null  int64
 15   dist_CH_To_BS    374661 non-null  float64
 16   send_code        374661 non-null  int64
 17  Expaned Energy    374661 non-null  float64
 18  Attack type       374661 non-null  object
dtypes: float64(3), int64(15), object(1)
memory usage: 54.3+ MB

In [3]:
df.describe()

,id,Time,Is_CH,who CH,Dist_To_CH,ADV_S,ADV_R,JOIN_S,JOIN_R,SCH_S,SCH_R,Rank,DATA_S,DATA_R,Data_Sent_To_BS,dist_CH_To_BS,send_code,Expaned Energy
count,3.746610e+05,374661.000000,374661.000000,3.746610e+05,374661.000000,374661.000000,374661.000000,374661.000000,374661.000000,374661.000000,374661.000000,374661.000000,374661.000000,374661.000000,374661.000000,374661.000000,374661.000000,374661.000000
mean,2.749693e+05,1064.748712,0.115766,2.749804e+05,22.599380,0.267698,6.940562,0.779905,0.737493,0.288984,0.747452,9.687104,44.857925,73.890045,4.569448,22.562735,2.497957,0.305661
std,3.898986e+05,899.646164,0.319945,3.899112e+05,21.955794,2.061148,7.044319,0.414311,4.691498,2.754746,0.434475,14.681901,42.574464,230.246335,19.679155,50.261604,2.407337,0.669462
min,1.010000e+05,50.000000,0.000000,1.010000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.070930e+05,353.000000,0.000000,1.070960e+05,4.735440,0.000000,3.000000,1.000000,0.000000,0.000000,0.000000,1.000000,13.000000,0.000000,0.000000,0.000000,1.000000,0.056150
50%,1.160710e+05,803.000000,0.000000,1.160720e+05,18.372610,0.000000,5.000000,1.000000,0.000000,0.000000,1.000000,3.000000,35.000000,0.000000,0.000000,0.000000,2.000000,0.097970
75%,2.150720e+05,1503.000000,0.000000,2.150730e+05,33.776000,0.000000,7.000000,1.000000,0.000000,0.000000,1.000000,13.000000,62.000000,0.000000,0.000000,0.000000,4.000000,0.217760
max,3.402096e+06,3600.000000,1.000000,3.402100e+06,214.274620,97.000000,117.000000,1.000000,124.000000,99.000000,1.000000,99.000000,241.000000,1496.000000,241.000000,201.934940,15.000000,45.093940

In [4]:
df['Attack type'].value_counts()

Attack type
Normal       340066
Grayhole      14596
Blackhole     10049
TDMA           6638
Flooding       3312
Name: count, dtype: int64

In [5]:
df['Attack type']=df['Attack type'].map({'Normal':0,'Grayhole':1,'Blackhole':2,'TDMA':3,'Flooding':4})

In [6]:
df['Attack type'].value_counts()

Attack type
0    340066
1     14596
2     10049
3      6638
4      3312
Name: count, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
from sklearn.tree import DecisionTreeClassifier

In [8]:
#df=df.drop('id',axis=1)
x=df.drop('Attack type',axis=1)
y=df['Attack type']

In [9]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
model=DecisionTreeClassifier()
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [11]:
y_pred=model.predict(x_test)
print("accuracy_score ",accuracy_score(y_test,y_pred))

accuracy_score  0.9949688388293543

In [12]:
model=GaussianNB()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print("accuracy_score ",accuracy_score(y_test,y_pred))
rep = classification_report(y_test, y_pred)
print(rep)

accuracy_score  0.8486247714625065
              precision    recall  f1-score   support

           0       0.99      0.87      0.93     67965
           1       0.18      0.51      0.26      3002
           2       0.56      0.93      0.70      2024
           3       0.86      0.37      0.52      1286
           4       0.22      0.85      0.35       656

    accuracy                           0.85     74933
   macro avg       0.56      0.71      0.55     74933
weighted avg       0.94      0.85      0.88     74933

In [13]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print("accuracy_score ",accuracy_score(y_test,y_pred))
rep = classification_report(y_test, y_pred)
print(rep)

accuracy_score  0.9972241869403333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     67965
           1       0.99      0.99      0.99      3002
           2       0.99      1.00      0.99      2024
           3       1.00      0.93      0.96      1286
           4       0.95      0.99      0.97       656

    accuracy                           1.00     74933
   macro avg       0.99      0.98      0.98     74933
weighted avg       1.00      1.00      1.00     74933

In [14]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print("accuracy_score ",accuracy_score(y_test,y_pred))
rep = classification_report(y_test, y_pred)
print(rep)

accuracy_score  0.9975578183176972
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     67965
           1       0.99      0.99      0.99      3002
           2       0.99      1.00      0.99      2024
           3       1.00      0.93      0.96      1286
           4       0.97      0.99      0.98       656

    accuracy                           1.00     74933
   macro avg       0.99      0.98      0.98     74933
weighted avg       1.00      1.00      1.00     74933